### ISSUE TITLE
Right-clicking a link and copying it doesn't work in Windows

### ISSUE THREAD

**Issue by sharma** [irccloud/irccloud-desktop#104]
**Issue:** When I right-click a hyperlink in a channel and select 'Copy Link Address' the link isn't actually copied to my clipboard. This appears to be a Windows-only issue as it seems to work as intended on macOS. 

**Version:** Noticed it happening on both 0.3.0 and 0.4.0. Windows 10 64-bit.

**Comment by jwheare** [comment]
Thanks for the report. Should hopefully be fixed in the next release. If you're able to try building from source to confirm that would be really helpful but don't worry if not.

**Comment by jarcane** [comment]
Can confirm this is fixed on 0.5.1 for me under Win10.
