### ISSUE TITLE
Blue line at bottom of window - windows 10 version 0.6.0

### ISSUE THREAD

**Issue by badken** [irccloud/irccloud-desktop#109]
![image](https://user-images.githubusercontent.com/15618935/35724748-1d189afa-07bc-11e8-87d8-53034b28cc80.png)

**Comment by jwheare** [comment]
This looks like a scrollbar. Unfortunately we have a minimum width for the app and you'll need to resize the window a tiny bit to get rid of this. Let me know if that doesn't do the trick.
