### ISSUE TITLE
IRCCloud Helper eats memory (macOS)

### ISSUE THREAD

**Issue by nkaretnikov** [irccloud/irccloud-desktop#111]
From time to time (approx. once in ten days), the fans in my laptop become noticeably louder. I think this is started when I installed IRCCloud Desktop.  It happened again yesterday, so I checked the Memory  tab in the Activity Monitor. It showed that IRCCloud Helper used 2,26GB of memory. I immediately killed it, and the noise disappeared. I haven't investigated, do you have an idea why this might happen?

**Comment by lyndsysimon** [comment]
I've come to expect this from Electron apps, unfortunately. It seems like they require extensive optimization to keep them from becoming resource hogs.

As a stopgap, I just make a point to restart all of them (including IRCCloud) every day or so. It seems to help.
