### ISSUE TITLE
macOS: clicking on a link opens the homepage

### ISSUE THREAD

**Issue by nkaretnikov** [irccloud/irccloud-desktop#112]
My default browser is Google Chrome. Whenever I click on a link, a new window pops up with the homepage (Google search). I seem to recall that it works from time to time (might be a false memory), but I cannot provide any specifics.

**Comment by jwheare** [comment]
I've seen this happen with Chrome from our app as well as others. Restarting chrome fixes it. Don't think the bug is on our side. Can you check clicking links from other apps opens a chrome tab correctly?

**Comment by nkaretnikov** [comment]
@jwheare, yep, it has something to do with Chrome (or maybe system permissions). Sorry for the noise.

**Comment by nkaretnikov** [comment]
Chrome -> about Google Chrome -> relaunch fixed it:
https://apple.stackexchange.com/a/306043
