### ISSUE TITLE
Can't zoom in or out

### ISSUE THREAD

**Issue by mythmon** [irccloud/irccloud-desktop#118]
Pressing ctrl+= or ctrl+- doesn't zoom in or out. Changing the `zoom` field in `config.json` also has no affect. I see that the hotkeys change the value in `config.json`.

**Comment by jwheare** [comment]
Which OS? Can't reproduce in Windows.

**Comment by mythmon** [comment]
I'm running Arch Linux.

**Comment by jwheare** [comment]
Which version? The aur version is quite out of date, uploaded by a 3rd party and not supported. If that’s what you’re using, please let me know if it still doesn’t work building from source.

**Comment by mythmon** [comment]
When building from source, the zoom works as expected.

I've flagged the Arch package as out of date. Do you have any interest in maintaining an Arch package, if that one goes away and/or becomes officially orphaned (it's maintainer gives it up)?

**Comment by jwheare** [comment]
We don't really have the resources to maintain a build setup for Arch at the moment, but we might in future. We do provide AppImage builds, and might support flatpak in future as well.

**Comment by jwheare** [comment]
Oh, and thanks very much for testing and verifying the latest build works :)

**Comment by carstenhag** [comment]
Hey, I'm on 0.7.2 and win10 x64, but I can not zoom in with `Ctrl + +` at all.

Zooming out doesn't work either, with the keyboard shortcuts.

Using the menu to do it works.

**Comment by jwheare** [comment]
@carstenhag I cant reproduce this on Windows 10. Is there a chance you're using software or have a setting that intercepts this key combo for another purpose?
