### ISSUE TITLE
Add ability to search backlog 

### ISSUE THREAD

**Issue by robbyoconnor** [irccloud/irccloud-desktop#125]
One of the major pain points of using irccloud, however great it is -- is that it's hard to search/grep the backlog...is it possible to add support to do so? 

For example, quickly and easily jump to mentions, etc.

**Comment by jwheare** [comment]
This is a planned feature of the service, but I can't give an ETA. Since this bug tracker is for the desktop wrapper only and not the service as a whole I'm closing this issue, but thanks for suggestion.
