### ISSUE TITLE
Mixed HTTPS and HTTP content prevent loading HTTP images

### ISSUE THREAD

**Issue by spalger** [irccloud/irccloud-desktop#13]
Unlink irccloud.com, HTTP links can not be embedded when irccloud.com is served over HTTPS to electron and those links are to HTTP resources.

 1. I've found two options, include the `Content-Security-Policy-Report-Only` header in server responses as described here: https://developers.google.com/web/fundamentals/security/prevent-mixed-content/fixing-mixed-content?hl=en
 2. Just disable web-security features :fried_shrimp: (originating issue: https://github.com/atom/electron/issues/2076)

I would be happy to implement 2), as it's [dead simple](https://github.com/atom/electron/issues/384) to do, but I feel like more security minded individuals should asses that decision.

**Comment by spalger** [comment]
:+1:

**Comment by atorralb** [comment]
where do you place it nodejs code or in the command line for windows? I can't seem to get it to work
