### ISSUE TITLE
/version fails to show all lines

### ISSUE THREAD

**Issue by impredicative** [irccloud/irccloud-desktop#135]
When I send `/version` on Freenode using IRCCloud, I get only the first line of the output. I should be getting all lines back instead. Freenode Webchat gives me four lines of output, for example.

If this issue has been filed in the wrong place, kindly advise exactly where I should file it instead. Thanks.

**Comment by jwheare** [comment]
Thanks for the report. I believe I answered this on IRC. This issue tracker is just for the desktop app wrapper, not for issues that affect the web app in general.

**Comment by impredicative** [comment]
Is there a different repo for the web app?

**Comment by jwheare** [comment]
There isn't, we don't have a public tracker for that and it's not an open source project. However, you can report issues to us on IRC or email team@irccloud.com

**Comment by impredicative** [comment]
Okay. I acknowledge it's not open source. I think it'll nevertheless be very helpful to have a dummy repo for it under the same organization, just to allow users to file/track issues. I understand you already have a private issue tracker for it, so I don't know how to reconcile the two. Thanks.
