### ISSUE TITLE
installation fails on fedora 25

### ISSUE THREAD

**Issue by ambarus** [irccloud/irccloud-desktop#139]
npm ERR! Linux 4.13.16-100.fc25.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "run" "dist"
npm ERR! node v6.12.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! irccloud-desktop@0.11.0 dist: `electron-builder`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the irccloud-desktop@0.11.0 dist script 'electron-builder'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the irccloud-desktop package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-builder
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs irccloud-desktop
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls irccloud-desktop
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/atudor/Downloads/irccloud-desktop-master/npm-debug.log
Makefile:7: recipe for target 'dist' failed
make: *** [dist] Error 1
[atudor@localhost irccloud-desktop-master]$  npm bugs irccloud-desktop
npm ERR! Linux 4.13.16-100.fc25.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "bugs" "irccloud-desktop"
npm ERR! node v6.12.0
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 Not found : irccloud-desktop
npm ERR! 404 
npm ERR! 404  'irccloud-desktop' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/atudor/Downloads/irccloud-desktop-master/npm-debug.log
[atudor@localhost irccloud-desktop-master]$ npm owner ls irccloud-desktop
npm ERR! owner ls Couldn't get owner data irccloud-desktop
npm ERR! Linux 4.13.16-100.fc25.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "owner" "ls" "irccloud-desktop"
npm ERR! node v6.12.0
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 Not found : irccloud-desktop
npm ERR! 404 
npm ERR! 404  'irccloud-desktop' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/atudor/Downloads/irccloud-desktop-master/npm-debug.log

cat /home/atudor/Downloads/irccloud-desktop-master/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'owner',
1 verbose cli   'ls',
1 verbose cli   'irccloud-desktop' ]
2 info using npm@3.10.10
3 info using node@v6.12.0
4 silly mapToRegistry name irccloud-desktop
5 silly mapToRegistry using default registry
6 silly mapToRegistry registry https://registry.npmjs.org/
7 silly mapToRegistry data Result {
7 silly mapToRegistry   raw: 'irccloud-desktop',
7 silly mapToRegistry   scope: null,
7 silly mapToRegistry   escapedName: 'irccloud-desktop',
7 silly mapToRegistry   name: 'irccloud-desktop',
7 silly mapToRegistry   rawSpec: '',
7 silly mapToRegistry   spec: 'latest',
7 silly mapToRegistry   type: 'tag' }
8 silly mapToRegistry uri https://registry.npmjs.org/irccloud-desktop
9 verbose request uri https://registry.npmjs.org/irccloud-desktop
10 verbose request no auth needed
11 info attempt registry request try #1 at 10:08:18 AM
12 verbose request id 833fe1379f82ecbe
13 http request GET https://registry.npmjs.org/irccloud-desktop
14 http 404 https://registry.npmjs.org/irccloud-desktop
15 verbose headers { date: 'Mon, 13 May 2019 07:08:18 GMT',
15 verbose headers   'content-type': 'application/json',
15 verbose headers   'content-length': '21',
15 verbose headers   connection: 'keep-alive',
15 verbose headers   'set-cookie': [ '__cfduid=dc9ba30a09b982a139957f0d1f1e20f6b1557731297; expires=Tue, 12-May-20 07:08:17 GMT; path=/; domain=.registry.npmjs.org; HttpOnly' ],
15 verbose headers   'cf-cache-status': 'MISS',
15 verbose headers   'cache-control': 'max-age=300',
15 verbose headers   'cf-ray': '4d62cce44972acca-OTP',
15 verbose headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
15 verbose headers   vary: 'accept-encoding, accept',
15 verbose headers   server: 'cloudflare' }
16 silly get cb [ 404,
16 silly get   { date: 'Mon, 13 May 2019 07:08:18 GMT',
16 silly get     'content-type': 'application/json',
16 silly get     'content-length': '21',
16 silly get     connection: 'keep-alive',
16 silly get     'set-cookie': [ '__cfduid=dc9ba30a09b982a139957f0d1f1e20f6b1557731297; expires=Tue, 12-May-20 07:08:17 GMT; path=/; domain=.registry.npmjs.org; HttpOnly' ],
16 silly get     'cf-cache-status': 'MISS',
16 silly get     'cache-control': 'max-age=300',
16 silly get     'cf-ray': '4d62cce44972acca-OTP',
16 silly get     'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
16 silly get     vary: 'accept-encoding, accept',
16 silly get     server: 'cloudflare' } ]
17 error owner ls Couldn't get owner data irccloud-desktop
18 verbose stack Error: Not found : irccloud-desktop
18 verbose stack     at makeError (/usr/lib/node_modules/npm/node_modules.bundled/npm-registry-client/lib/request.js:302:12)
18 verbose stack     at CachingRegistryClient.<anonymous> (/usr/lib/node_modules/npm/node_modules.bundled/npm-registry-client/lib/request.js:290:14)
18 verbose stack     at Request._callback (/usr/lib/node_modules/npm/node_modules.bundled/npm-registry-client/lib/request.js:210:14)
18 verbose stack     at Request.self.callback (/usr/lib/node_modules/npm/node_modules.bundled/request/request.js:187:22)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at Request.emit (events.js:191:7)
18 verbose stack     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules.bundled/request/request.js:1048:10)
18 verbose stack     at emitOne (events.js:96:13)
18 verbose stack     at Request.emit (events.js:188:7)
18 verbose stack     at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm/node_modules.bundled/request/request.js:969:12)
19 verbose statusCode 404
20 verbose pkgid irccloud-desktop
21 verbose cwd /home/atudor/Downloads/irccloud-desktop-master
22 error Linux 4.13.16-100.fc25.x86_64
23 error argv "/usr/bin/node" "/usr/bin/npm" "owner" "ls" "irccloud-desktop"
24 error node v6.12.0
25 error npm  v3.10.10
26 error code E404
27 error 404 Not found : irccloud-desktop
28 error 404
29 error 404 'irccloud-desktop' is not in the npm registry.
30 error 404 You should bug the author to publish it (or use the name yourself!)
31 error 404 Note that you can also install from a
32 error 404 tarball, folder, http url, or git url.
33 verbose exit [ 1, true ]

**Comment by jwheare** [comment]
Looks like you’re running an old version of node. You need at least the latest 8.x release to build this. The debug log you sent only contains info on the non-bug that the app is not in the npm registry.

**Comment by ambarus** [comment]
Indeed, I updated to nodejs 10.x and it works. Thanks!
