### ISSUE TITLE
Unable to right click/copy links

### ISSUE THREAD

**Issue by wizardfrag** [irccloud/irccloud-desktop#14]
Right click appears to be disabled for some reason

**Comment by wizardfrag** [comment]
Seems to be being caused by https://github.com/irccloud/irccloud-desktop/blob/9a6a9d91a1cb0e283d706e9f75a3820b62cc4226/app/preload.js#L32-L34

Is there a reason for this?

**Comment by russss** [comment]
Added a basic menu in 9dc148658948c6df504e9c5af0031ee25c3a571e.
