### ISSUE TITLE
deb 0.13.0 fails to start

### ISSUE THREAD

**Issue by TBSliver** [irccloud/irccloud-desktop#144]
```
$ irccloud 
[27350:0725/122534.603230:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/IRCCloud/chrome-sandbox is owned by root and has mode 4755.
```

This is on a freshly installed version...

**Comment by TBSliver** [comment]
Note that performing `chmod 4755 /opt/IRCCloud/chrome-sandbox` fixes it, but that shouldnt be required on a fresh install tbh...

**Comment by jwheare** [comment]
Thanks for the report, this seems to be blocked upstream, but I'll see if I can figure out a reliable workaround in our build process:

https://github.com/electron/electron/issues/17972
https://github.com/electron-userland/electron-builder/issues/3872

**Comment by jwheare** [comment]
0.14.0 is now released. Could check if this is still an issue?

**Comment by TBSliver** [comment]
Well, it didnt fail to start after updating, so doesnt seem to be an issue anymore. Excellent :D Thanks for updating me on this :+1:
