### ISSUE TITLE
.deb requires unnecessary dependencies (gir1.2-gnomekeyring-1.0)

### ISSUE THREAD

**Issue by aerth** [irccloud/irccloud-desktop#146]
_OS: Debian 10 (buster)_

currently, the .deb file "works", as in... there is system integration (icons, menus) and the app opens and is able to be used... **but** breaks all future dpkg and apt commands until removing the half-installed package (as seen here)

```
The following packages have unmet dependencies:
 irccloud-desktop : Depends: gir1.2-gnomekeyring-1.0 but it is not installable
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

below is the output of installation attempt.

```
sudo dpkg -i irccloud-desktop_0.13.0_linux_amd64.deb 
Selecting previously unselected package irccloud-desktop.
(Reading database ... 319014 files and directories currently installed.)
Preparing to unpack irccloud-desktop_0.13.0_linux_amd64.deb ...
Unpacking irccloud-desktop (0.13.0-362) ...
dpkg: dependency problems prevent configuration of irccloud-desktop:
 irccloud-desktop depends on gir1.2-gnomekeyring-1.0; however:
  Package gir1.2-gnomekeyring-1.0 is not installed.

dpkg: error processing package irccloud-desktop (--install):
 dependency problems - leaving unconfigured
Processing triggers for desktop-file-utils (0.23-4) ...
Processing triggers for mime-support (3.62) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 irccloud-desktop
```

Meanwhile, the .AppImage works fine, but doesn't install in system menus/icons

**Comment by vectr0n** [comment]
A fix for this would be greatly appreciated...

**Comment by RevoluPowered** [comment]
got the same issue 

```
$ sudo dpkg -i irccloud-desktop_0.13.0_linux_amd64.deb
(Reading database ... 243640 files and directories currently installed.)
Preparing to unpack irccloud-desktop_0.13.0_linux_amd64.deb ...
Unpacking irccloud-desktop (0.13.0-362) over (0.13.0-362) ...
dpkg: dependency problems prevent configuration of irccloud-desktop:
 irccloud-desktop depends on gir1.2-gnomekeyring-1.0; however:
  Package gir1.2-gnomekeyring-1.0 is not installed.

dpkg: error processing package irccloud-desktop (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.32.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu1) ...
Processing triggers for mime-support (3.63ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
```

tried installing manually the missing deps.

**Comment by jwheare** [comment]
I'm hoping this will be fixed in the upcoming 0.14.0, but that still has a few blockers before it can be released.

**Comment by jwheare** [comment]
0.14.0 is now released. Could check if this is still an issue?

**Comment by aerth** [comment]
the 0.14.0 release fixes this issue

but seeing how it downloads an AppImage immediately upon opening the program I don't see the point of using the .deb file... May just stick with AppImage for now
![image](https://user-images.githubusercontent.com/6263105/75409271-3994d900-58e6-11ea-8798-e91664346d63.png)

**Comment by jwheare** [comment]
Hmm, the auto-updater is supposed to be disabled on non-appimage linux builds. Can you inspect the env of the running process (using `/proc/PID/environ` or `ps eww PID`) to see if it has the `APPIMAGE` var set?

**Comment by jwheare** [comment]
Closing this as the original issue is resolved.
