### ISSUE TITLE
the Minimum width of irccloud makes it almost impossible to use on small displays

### ISSUE THREAD

**Issue by gordallott** [irccloud/irccloud-desktop#148]
Small displays are often shorter than the minimum width enforced by irccloud, personally my chromebook almost hits the minimum width even when fullscreen

The minimum width of irccloud is completely unneeded, much like on the mobile platforms it could be much thinner, as well as the sidebar could (and should) be togglable rather than always on taking up a significant amount of space 

removing the completely unnecessary min-width from div#container in the css would resolve this problem and be a quick solution that would make a lot of people happy

with my own testing disabling that there are no visual errors, it's just better and nicer

**Comment by jwheare** [comment]
We'll bear this in mind. This issue tracker is only for the desktop wrapper. We don't track requests/issues here that also affect the web app in the browser.

**Comment by gordallott** [comment]
yes, i realise that, but it is not obvious where to track that 

in addition, i can fix this on the web with userstyles, i can't fix this on the desktop so I feel it does affect the desktop

**Comment by jwheare** [comment]
Fwiw, you can use user styles with the desktop app by placing a `user-style.css` file alongside the config file, i.e.

* `%APPDATA%\IRCCloud` on Windows
* `$XDG_CONFIG_HOME/IRCCloud` or `~/.config/IRCCloud` on Linux
* `~/Library/Application Support/IRCCloud` on macOS

`user-script.js` also works in the same manner.

We should document this better.
