### ISSUE TITLE
Please include time zones in the timestamps in an export

### ISSUE THREAD

**Issue by offby1** [irccloud/irccloud-desktop#149]
I'm looking at a line from an export that I recently made:
```
[2019-10-27 03:13:07] <dredsss_> hello
```
Is that 3:13:07 in the morning _my_ time, the time in the area your server is located, or what?  How am I supposed to know?

Please use RFC3339 timestamps, including the time zone.

**Comment by jwheare** [comment]
The timestamps are in the time zone that you selected when you downloaded the logs, which defaults to your time as reported by the browser.
