### ISSUE TITLE
MacOS: app is blank in Mission Control

### ISSUE THREAD

**Issue by dpslwk** [irccloud/irccloud-desktop#151]
Since 0.11 IRC cloud is just a white screen in mission control 
Found out there are related issues in Electron

https://github.com/electron/electron/issues/19430

I always run in full screen and use Mission Controller heavily, big white tile is annoying
For now I keep having to down grade to 0.10, (any way to stop auto update?)

<img width="289" alt="Screenshot 2019-10-31 at 13 33 35" src="https://user-images.githubusercontent.com/234460/67951478-7e805b80-fbe3-11e9-857c-20d12e275207.png">

**Comment by jwheare** [comment]
There's no way to stop auto update I'm afraid. We'll track the upstream issue, thanks for letting us know.

**Comment by dpslwk** [comment]
this appears fixed as of v14 and the update to electron 8
