### ISSUE TITLE
Flatpak support

### ISSUE THREAD

**Issue by barthalion** [irccloud/irccloud-desktop#152]
Hi,

I've prepared flatpak manifest that could be published to [Flathub](https://flathub.org): https://github.com/barthalion/flatpak-irccloud

One of submission prerequisites is interest from upstream in (co-)maintenance. Is that something you would consider?

**Comment by jwheare** [comment]
Yes, we'd be interested in co-maintaining this, although we have zero experience with the faltpak ecosystem.

Looking at https://github.com/flathub/com.irccloud.desktop it seems like a lot of boiilerplate. Can this be easily generated instead of hardcoded somehow?

**Comment by jwheare** [comment]
Potentially useful docs for (my) future ref

https://github.com/electron-userland/electron-builder/issues/512
https://docs.flatpak.org/en/latest/electron.html

**Comment by barthalion** [comment]
I have invited you to collaborators, you can view the invite here: https://github.com/flathub/com.irccloud.desktop/invitations

Yeah, at the moment electron-builder lacks support for Flatpak. https://github.com/flathub/com.irccloud.desktop/blob/8338dbd05cf5fa17020eea17a67548ddd90b2d06/com.irccloud.desktop.json#L91 specifies which commit the app gets build from.

Ideally https://github.com/flathub/com.irccloud.desktop/blob/master/irccloud.desktop and https://github.com/flathub/com.irccloud.desktop/blob/master/irccloud.metainfo.xml should be maintained in your repository so everyone else can also benefit, although I guess desktop file is generated automatically by electron-builder.

**Comment by jwheare** [comment]
The desktop file is now generated here https://github.com/irccloud/irccloud-desktop/blob/master/build/irccloud.desktop

**Comment by barthalion** [comment]
Thanks. I'll look into preparing the upgrade today.

**Comment by barthalion** [comment]
Pushed to beta branch, will use it for few days and merge to stable.

**Comment by jwheare** [comment]
Please hold off merging to stable until we can get 0.14.0 released fully. See #154

**Comment by jwheare** [comment]
Also note that the desktop file specifies a hardcoded Exec path:

`Exec=/opt/IRCCloud/irccloud --no-sandbox %U`

**Comment by barthalion** [comment]
Ack. I noticed, changed it to wrapper script which also allows to use Electron sandbox with [zypak](https://github.com/refi64/zypak). I can restore `--no-sandbox` if it's known to cause issues though.

**Comment by jwheare** [comment]
The --no-sandbox thing is to resolve this issue #144 which may or may not be present when using zypak, but I see it has a `ZYPAK_DISABLE_SANDBOX=1` option in case it does.

**Comment by jwheare** [comment]
0.14.0 is released now.

**Comment by barthalion** [comment]
Sorry, I was on vacation. Just pushed 0.14.1 to Flathub stable.

**Comment by jwheare** [comment]
Thanks. In future would be good if we can just bundle publishing a new flatpak into our build process directly.
