### ISSUE TITLE
Websocket issue?

### ISSUE THREAD

**Issue by seitzbg** [irccloud/irccloud-desktop#160]
I get this on both wired/wireless:

![image](https://user-images.githubusercontent.com/171158/93803495-f3e98600-fc12-11ea-94a8-644e671d0797.png)

Latest version.   Please advise.

**Comment by jwheare** [comment]
This is an ongoing server side issue and not a problem with the desktop app. See https://twitter.com/IRCCloud/status/1307785997736988673
