### ISSUE TITLE
Provide build for Apple Silicon m1

### ISSUE THREAD

**Issue by diddledan** [irccloud/irccloud-desktop#165]
Currently the built releases are Intel-only for macOS builds. This issue is documenting the need for an Apple Silicon build or a Universal Binary build to be used on the new m1-based Apple Macs.

**Comment by jwheare** [comment]
This is done but still pending release. CI issues... probably gonna switch over to github actions.

**Comment by jwheare** [comment]
0.16.0 is now released as a universal binary https://github.com/irccloud/irccloud-desktop/releases/tag/v0.16.0
