### ISSUE TITLE
no support for windows or PCs

### ISSUE THREAD

**Issue by MyTDT-Mysoft** [irccloud/irccloud-desktop#171]
really? you call that you have a desktop app, that is not even a desktop app just a retarded electron interface... and that does not work on any version of windows that is not bloated with crap... and then it says its for PCs... but it does not work on PCs... requiring retarded 64bits... can you please fix that?

**Comment by jwheare** [comment]
We stopped supporting 32 bit builds, but you can build it yourself from source.
