### ISSUE TITLE
Use a custom login/signup screen

### ISSUE THREAD

**Issue by russss** [irccloud/irccloud-desktop#25]
We can probably assume that if a user has downloaded the app, they know vaguely what IRCCloud is, so it would be nice to show a simpler, more "app"-looking login/signup screen on first load, rather than the IRCCloud home page.

**Comment by russss** [comment]
I think there is an issue with this still - the first time I load the app (with no user settings) it shows me the standard homepage. Closing and re-opening shows me the streamlined login.

**Comment by jwheare** [comment]
Is there a message in ~/Libary/Logs/IRCCloud/log.log that says `set invite cookie error`?

**Comment by jwheare** [comment]
There is an issue I'm aware of where you get returned to the standard home page if you manually log out, which might also happen if your session cookie has been invalidated since the last time you used the app.

**Comment by ChickenNuggers** [comment]
Perhaps this can be fixed with adding something onto the website that shows an optional streamlined login? From there, you just have to load a different URL.
