### ISSUE TITLE
Annoying Notifications

### ISSUE THREAD

**Issue by dannymichel** [irccloud/irccloud-desktop#30]
I really cant stand the notifications my IRCCloud app makes. I mean, i do want notifications, but not in the middle of my screen. Is this something I can control?
![screenshot from 2016-05-04 08-54-14](https://cloud.githubusercontent.com/assets/1161544/15014949/0137356c-11d7-11e6-85e5-8aae1f80900a.png)

**Comment by jwheare** [comment]
We've just released an update with an updated Electron. Can you try it and see if this is still happening? http://desktop.irccloud.com/

**Comment by jwheare** [comment]
This issue was supposedly upstream here: https://github.com/electron/electron/issues/465#event-625578014

If it's not fixed, there's a workaround listed in that thread here: https://github.com/electron/electron/issues/465#issuecomment-206582829

**Comment by dannymichel** [comment]
Perfect
