### ISSUE TITLE
Icon broken in Linux

### ISSUE THREAD

**Issue by charliewolf** [irccloud/irccloud-desktop#32]
This commit: f30cfdb2c0916014bcb1520f971341c6e94b25c6 seems to have broken the icon in Linux.

I have a patch ready to submit a PR as soon as Github is done fixing the database issues they are having that are preventing me from opening a PR.

**Comment by jwheare** [comment]
Thanks. This was changed because the png scaled down badly on Windows. Your patch will need to make sure that isn't regressed.

**Comment by charliewolf** [comment]
It still uses ico on windows
 
On Mon, May 23, 2016, at 12:46 PM, James Wheare wrote:
> Thanks. This was changed because the png scaled down badly on Windows.
> Your patch will need to make sure that isn't regressed.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub[1]
>
 

Links:

  1. https://github.com/irccloud/irccloud-desktop/issues/32#issuecomment-221041352
