### ISSUE TITLE
Uncaught EPERM when resizing the window

### ISSUE THREAD

**Issue by rcsheets** [irccloud/irccloud-desktop#42]
Running version 0.1.7 on Win10 (10586.420) on x64, I sometimes see the following uncaught exception immediately after resizing the window:

```
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: EPERM: operation not permitted, rename 'C:\Users\rcshe\.config\configstore\IRCCloud.json.677343039' -> 'C:\Users\rcshe\.config\configstore\IRCCloud.json'
    at Error (native)
    at Object.fs.renameSync (fs.js:729:18)
    at Function.writeFileSync [as sync] (C:\Users\rcshe\AppData\Local\IRCCloud\app-0.1.7\resources\app.asar\node_modules\write-file-atomic\index.js:39:8)
    at Object.create.all.set (C:\Users\rcshe\AppData\Local\IRCCloud\app-0.1.7\resources\app.asar\node_modules\configstore\index.js:63:21)
    at Object.Configstore.set (C:\Users\rcshe\AppData\Local\IRCCloud\app-0.1.7\resources\app.asar\node_modules\configstore\index.js:94:11)
    at BrowserWindow.<anonymous> (C:\Users\rcshe\AppData\Local\IRCCloud\app-0.1.7\resources\app.asar\main.js:93:12)
    at emitOne (events.js:90:13)
    at BrowserWindow.emit (events.js:182:7)

[OK]
```

After I dismiss the dialog box, the application appears to continue working normally. In particular, the attempt to resize the window succeeds.

**Comment by jwheare** [comment]
Do either of these files exist?

`C:\Users\rcshe.config\configstore\IRCCloud.json.677343039`
`C:\Users\rcshe.config\configstore\IRCCloud.json`

What are the permissions on them if so?

**Comment by rcsheets** [comment]
The `C:\Users\rcshe.config` directory does not exist. My `%USERPROFILE%` is `C:\Users\rcshe`

**Comment by rcsheets** [comment]
Sorry, it looks like my error message wasn't accurately copied into the issue, initially. I'm trying to fix that now.

**Comment by rcsheets** [comment]
I quoted when I should've used ```. Sorry about that. I've edited the initial comment so it should display properly now.

`C:\Users\rcshe\.config\configstore\IRCCloud.json` _does_ exist. Here are the relevant permissions:

```
C:\Users\rcshe\.config>icacls . /T
. NT AUTHORITY\SYSTEM:(OI)(CI)(F)
  BUILTIN\Administrators:(OI)(CI)(F)
  HUSKER\rcshe:(OI)(CI)(F)

.\configstore NT AUTHORITY\SYSTEM:(OI)(CI)(F)
              BUILTIN\Administrators:(OI)(CI)(F)
              HUSKER\rcshe:(OI)(CI)(F)

.\configstore\IRCCloud.json NT AUTHORITY\SYSTEM:(F)
                            BUILTIN\Administrators:(F)
                            HUSKER\rcshe:(F)

Successfully processed 3 files; Failed processing 0 files
```

Hope that helps.

**Comment by jwheare** [comment]
Thanks, I'll try to reproduce.

**Comment by jwheare** [comment]
Notes for myself:

This is happening when setting width and height in configstore. It could be the result of multiple attempts to set the value in quick succession, simple debouncing on the resize event handler might help.
