### ISSUE TITLE
Better user-style.css management

### ISSUE THREAD

**Issue by jwheare** [irccloud/irccloud-desktop#51]
Add a menu item to edit the CSS file in a prompt, and/or reveal/open in OS.

**Comment by pmac** [comment]
How might one find this file in the interim?

**Comment by KWierso** [comment]
Looks like you need to create a user-style.css file in the IRCCloud folder within the application data folder for your platform, as described here: https://github.com/irccloud/irccloud-desktop/issues/41#issuecomment-247166781

Then stick your custom CSS into that file and it should apply to the app the next time it restarts.

**Comment by pmac** [comment]
Worked perfectly. Thanks @KWierso! 💯

**Comment by jwheare** [comment]
Done in 97d8821a90f7efdce96c26d4ba1d5f7d4224dc9e

**Comment by jwheare** [comment]
Fixed in the latest release: https://github.com/irccloud/irccloud-desktop/releases/tag/v0.4.0
