### ISSUE TITLE
Emocodes parsing expects a space around emocodes

### ISSUE THREAD

**Issue by purukaushik** [irccloud/irccloud-desktop#52]
Emocodes that don't have  a space around them aren't rendered.

Example:
In github, `great:thumbsup:thanks` is rendered as

> great:thumbsup:thanks

while in irccloud the same is rendered as 
`great:thumbsbup:thanks`

**Comment by jwheare** [comment]
Thanks for the suggestion, but this isn't a general IRCCloud issue tracker, it's just for the desktop wrapper.
