### ISSUE TITLE
Don't quit on window close (macOS)

### ISSUE THREAD

**Issue by kudos** [irccloud/irccloud-desktop#54]
It's not standard behaviour on macOS to quit the app when the last window is closed.

**Comment by jwheare** [comment]
Some apps do though, e.g. System Preferences, App Store. Since this app has a single window, there's no need to keep the app running after the window is closed.

**Comment by kudos** [comment]
Some apps do, but no chat apps do. It may be a single window app, but it's also an app that does stuff in the background (stays connected to irc channels, notifies on messages, etc). I'm using Macs for over 10 years, and the CMD+W muscle memory for "I'm done with this app for now" is strong.

**Comment by jwheare** [comment]
So if you're done with the app, why shouldn't it quit? If it didn't quit and you came back to the app later, what should happen?

**Comment by kudos** [comment]
By not quitting the app I don't have to wait for the whole thing to load again. A good example is when I'm in a conversation with someone and I think it's done so I CMD+W. Then they reply again for some reason, firstly I don't know that since the app has quit, secondly I now need to wait for the app to load again, which takes ~10-20 seconds. The behaviour should be to hide the window (because the main thread of the app is effectively in the window process) instead of quit the app. If I want to quit I'll use CMD+Q instead.

**Comment by kudos** [comment]
And for comparison, Slack's Mac app which is also a web wrapper and only has one window behaves the  way I'm suggesting.

**Comment by jwheare** [comment]
At the moment, the main thread of the app is only in the window, so even if you close the window and the app stayed active, you wouldn't get any background benefit. We'll revisit this if that changes.

**Comment by kudos** [comment]
I know, to repeat what I said:

> The behaviour should be to hide the window (because the main thread of the app is effectively in the window process) instead of quit the app. If I want to quit I'll use CMD+Q instead.

**Comment by jwheare** [comment]
I opened a #56 to more fully describe the desired outcome.

**Comment by kudos** [comment]
Thanks!

**Comment by akashnimare** [comment]
@jwheare @kudos fixed in https://github.com/irccloud/irccloud-desktop/pull/57.
