### ISSUE TITLE
Linux App on desktop.irccloud.com Lacks an Icon

### ISSUE THREAD

**Issue by ddasilva** [irccloud/irccloud-desktop#59]
It would be nice if the program had an icon or a launcher that one could search the dash for in ubuntu. Right now, makes my toolbar look ugly with the default icon.

**Comment by jwheare** [comment]
Hmm, it should have one. Which Linux desktop are you running? Can you show a screenshot of the default icon in your toolbar?

**Comment by ddasilva** [comment]
Odd, not sure what the problem was but it has one now. Closing.
