### ISSUE TITLE
Error on startup on Linux

### ISSUE THREAD

**Issue by robbyoconnor** [irccloud/irccloud-desktop#61]
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from /opt/IRCCloud/resources/app.asar/icon.ico
    at TypeError (native)
    at setupTray (/opt/IRCCloud/resources/app.asar/main.js:179:13)
    at EventEmitter.<anonymous> (/opt/IRCCloud/resources/app.asar/main.js:200:7)
    at emitOne (events.js:95:20)
    at EventEmitter.emit (events.js:182:7)

**Comment by jwheare** [comment]
Which version/distribution of the app are you running?

**Comment by robbyoconnor** [comment]
0.1.7 on Linux Mint.

**Comment by robbyoconnor** [comment]
Fixed in 0.3.0. Closing. May wanna update the one in the README :smile:

**Comment by jwheare** [comment]
Sorry about that, it looks like our update server needs poking. It should be automatically serving the latest version.

**Comment by robbyoconnor** [comment]
It's all cool -- nobody using OSS is entitled to anything, myself included :) -- Great app.
