### ISSUE TITLE
Enable text substitutions on Mac

### ISSUE THREAD

**Issue by pmac** [irccloud/irccloud-desktop#62]
In OSX keyboard prefs you can set text substitutions that should work globally. Normally if they don't work with a text input box you can right-click and enable them. That is not available in the right-click menu for the message input box for this app. This may well be an electron issue, but I wanted to file here just in case this is something that can be enabled.

**Comment by jwheare** [comment]
Yup, looks like we can use this https://github.com/CharlieHess/electron-text-substitutions

**Comment by jwheare** [comment]
Well, I tried that package out but it's a bit of a hack and doesn't seem to work with our app. The reason this doesn't work out of the box is because it's missing from chromium. Might help to star this issue. https://bugs.chromium.org/p/chromium/issues/detail?id=42434

Closing this issue for now.
