### ISSUE TITLE
Half Zoom 

### ISSUE THREAD

**Issue by agence104** [irccloud/irccloud-desktop#67]
Hi,

Could we reduce the zoom size to half size. I feel as if the zooms are too big in differences.

Thank

**Comment by agence104** [comment]
From :
`app.zoomIn = function () {
  var newZoom = Math.min(maxZoom, config.get('zoom') + 1);
  updateZoom(newZoom);
};
app.zoomOut = function () {
  var newZoom = Math.max(minZoom, config.get('zoom') - 1);
  updateZoom(newZoom);
};`

To: 
app.zoomIn = function () {
  var newZoom = Math.min(maxZoom, config.get('zoom') + 0.5);
  updateZoom(newZoom);
};
app.zoomOut = function () {
  var newZoom = Math.max(minZoom, config.get('zoom') - 0.5);
  updateZoom(newZoom);
};

**Comment by agence104** [comment]
Any update on this issue?

**Comment by jwheare** [comment]
We've not been able to prioritise work on the desktop app recently, but I'm taking a look at it again this week. Will try to get a release out soon with a fix for this.

Note to self: look into https://github.com/electron/electron/pull/8041 as well.

**Comment by agence104** [comment]
Great News. Thanks. Ill keep an eye out :)

**Comment by jwheare** [comment]
Fixed in c4b3014, will be in the next release.

**Comment by jwheare** [comment]
Fixed in the latest release: https://github.com/irccloud/irccloud-desktop/releases/tag/v0.4.0
