### ISSUE TITLE
Remember preferences on macOS

### ISSUE THREAD

**Issue by paroxp** [irccloud/irccloud-desktop#68]
Hello!

Just a little bit annoying thing.

Each time I fire up IRCCloud, I need to make it fullscreen again, to use the multiple desktop feature on macOS.

Whilst, Atom or even iTerm remember my setting for the next time firing up.

Would be nice to consider as a fix.

Thanks.

**Comment by paroxp** [comment]
I'm guessing, it's somewhat related to #39.

Something, might have broken down?

**Comment by jwheare** [comment]
This should be fixed in 718a91a8d8a591583ba4d30cceeaf01ed68910bd, available in the next release.

**Comment by paroxp** [comment]
Great, thanks :)

**Comment by jwheare** [comment]
No probs. I'll close this once it's been fully tested on all platforms and released.

**Comment by jwheare** [comment]
Fixed in the latest release: https://github.com/irccloud/irccloud-desktop/releases/tag/v0.4.0
