### ISSUE TITLE
Add user script support

### ISSUE THREAD

**Issue by mikeconley** [irccloud/irccloud-desktop#70]
[I know of at least one user script](https://github.com/luser/irccloud-gifcommand) that I use periodically with IRCCloud. Having moved to the desktop client, I miss it. I can inject it after start-up by using the Developer Tools, but it'd be a lot easier if there was a way I could add user script just like I can add user style.

Thanks for all your work on IRCCloud and the desktop client. I'm a big fan!

**Comment by globau** [comment]
looks like this was resolved by 4d460cf and 97d8821

**Comment by mikeconley** [comment]
Indeed!

**Comment by jwheare** [comment]
Ah sorry, I meant to tag this issue earlier. Reopening until the new release has been pushed with this fix.

**Comment by jwheare** [comment]
Fixed in the latest release: https://github.com/irccloud/irccloud-desktop/releases/tag/v0.4.0
