### ISSUE TITLE
Key binding for 'View > Actual Size' doesn't work

### ISSUE THREAD

**Issue by genehack** [irccloud/irccloud-desktop#73]
The menu displays a '⌘0' shortcut next to 'Actual size', but pressing that doesn't change the font size -- probably because 'Window > Main Window' has that same shortcut and it grabs the key press. 

⌘0 is sort of the standard key for this sort of thing; probably the best fix is making the main window short cut ⌘1 or something.

**Comment by jwheare** [comment]
Fixed in 87b6ffa, will be in the next release.

**Comment by genehack** [comment]
thanks!

**Comment by jwheare** [comment]
Fixed in the latest release: https://github.com/irccloud/irccloud-desktop/releases/tag/v0.4.0
