### ISSUE TITLE
Background color glitch (electron/Chromium issue)

### ISSUE THREAD

**Issue by zvuc** [irccloud/irccloud-desktop#75]
![pasted_image_15_12_2016__10_34_am](https://cloud.githubusercontent.com/assets/2870726/21209017/23d01190-c2b5-11e6-8ab8-4218506cc67c.png)

There is a weird graphic glitch that displays same-color background as slightly different shades. It seems like it's an issue of electron (https://github.com/electron/electron/issues/7304) in turn which is an issue of chromium (https://bugs.chromium.org/p/chromium/issues/detail?id=633805). Other apps like Atom (https://github.com/atom/atom/issues/12634) VScode (https://github.com/Microsoft/vscode/issues/12473) that use electron seem to be affected by it.

IRCCloud desktop app is also affected by this, so when the related Chromium issue is fixed and electron is upgraded to Chromium 54, IRCCloud desktop app should be also recompiled with the updated version of electron that should hopefully fix this bug.

**Comment by jwheare** [comment]
Latest release is now out: https://github.com/irccloud/irccloud-desktop/releases/tag/v0.4.0
