### ISSUE TITLE
Actually allow disabling notifications per-channel/pm

### ISSUE THREAD

**Issue by InAnimaTe** [irccloud/irccloud-desktop#79]
Would be nice to disable getting notifications for a channel or pm that I am actively working in. This seems to be possible in the phone app but not for desktop. 

Thanks

**Comment by jwheare** [comment]
Thanks for the feedback. This is a feature for the web app in general that we're planning to work on. This project is dedicated to the desktop app wrapper so I'll close it here.

**Comment by InAnimaTe** [comment]
ohh derp. sorry about that. Which repo should I create this in?

**Comment by jwheare** [comment]
We don't have a public issue tracker for the web app. We're keeping track of it internally though.

**Comment by InAnimaTe** [comment]
Gotcha. Thanks!
