### ISSUE TITLE
Figure out automatic-upgrade process

### ISSUE THREAD

**Issue by Jonty** [irccloud/irccloud-desktop#8]
Electron supposedly provides this, but I've seen other electron apps in the OSX app store. Not sure.

**Comment by russss** [comment]
Electron has built-in [auto-updating support](http://electron.atom.io/docs/v0.36.8/api/auto-updater/) for Windows. Also more [app store details here](http://electron.atom.io/docs/v0.36.8/tutorial/mac-app-store-submission-guide/).

**Comment by jwheare** [comment]
Progress is happening here: https://github.com/irccloud/irccloud-desktop/compare/master...autoupdates

**Comment by jwheare** [comment]
Well, this works now.

**Comment by akashnimare** [comment]
Hey @jwheare 
Could you please tell me how are you handling auto updater feature in Linux?
I'm trying to add this feature in one of my electron app and was thinking to use [electron-gh-releases](https://github.com/jenslind/electron-gh-releases) which supports windows + Mac pretty well but I'm not sure what to do with linux 😭 .

**Comment by jwheare** [comment]
@akashnimare we're using GitbookIO/nuts but there may be better options these days, it has its quirks.

**Comment by akashnimare** [comment]
@jwheare Thanks 👍 .

**Comment by akashnimare** [comment]
@jwheare Btw [electron-gh-releases](https://github.com/jenslind/electron-gh-releases) looks promising.
