### ISSUE TITLE
what are we supposed to do with a .nupkg file?

### ISSUE THREAD

**Issue by diddledan** [irccloud/irccloud-desktop#84]
The Windows downloadable from desktop.irccloud.com is a .nupkg file which Windows cannot run. 0.2.0 included a .exe installer which does work. Checking for updates in the 0.2.0 installation from exe fails even though it should update to 0.3.0, presumably because squirrel also doesn't understand how to work with a nupkg.

**Comment by jwheare** [comment]
Sorry about this. We had to remove the 0.3.0 exe because it was accidentally overwritten. I've re-run the build and published it again. Could you check that it works now?

**Comment by diddledan** [comment]
thanks. I can confirm auto update and the desktop.irccloud.com are correctly working as expected. Awesome turnaround time there 🥇👍👍👍
