### ISSUE TITLE
Forward/back mouse buttons don't work on Linux

### ISSUE THREAD

**Issue by dpedu** [irccloud/irccloud-desktop#86]
I'm running Irccloud Desktop on Ubuntu 16.04, within the Gnome 3 desktop environment. I have a mouse with forward/back buttons that worked out-of-the-box on Firefox and Chromium. But Irccloud Desktop does not respond to them.

The version of the installed debian package is 0.3.0-181.

**Comment by jwheare** [comment]
There's an upstream issue with electron to support this here: electron/electron#6996

Failing that, someone wrote a module to handle this that we might be able to use https://github.com/jostrander/mouse-forward-back

**Comment by jwheare** [comment]
Fixed in electron 5.0 #15441

**Comment by jwheare** [comment]
Double action issue, issue reported here electron/electron#18322

**Comment by jwheare** [comment]
They apparently just work without these commands.
