### ISSUE TITLE
Highlights hangs the client

### ISSUE THREAD

**Issue by jnylen** [irccloud/irccloud-desktop#89]
Hi,
Using Manjaro Deepin.

On every highlight the desktop client crashes and have to be forced to close. Sometimes the highlight doesnt crash the client, sometimes it does.

**Comment by troix1** [comment]
Same here, most of the times when someone tags me and I see notification in bottom right corner it freezes and I need to end the process. Makes the app kinda unusable but otherwise I really like it and I'm using it on the phone too. Fix please!

**Comment by jnylen** [comment]
@troix1,
Seems fixed after I changed from Manjaro to pure Arch.

**Comment by jnylen** [comment]
This isn't fixed so I changed to hex chat. FYI
