### ISSUE TITLE
Windows desktop client doesn't do display scaling

### ISSUE THREAD

**Issue by DavieDavieDave** [irccloud/irccloud-desktop#91]
The Windows desktop client doesn't do WIndows display scaling at all. I have a 4K display and have scaling set to 125%, however when the desktop client launches, it does not set the font size appropriately and remains as if scaling was on 100%. Changing the font size is not remembered when the application is restarted. Also changing channels when the font has been increased sometimes causes the font to reduce to it's original size.

**Comment by jwheare** [comment]
Hi, could you let me know if this still happens with the latest app release? https://github.com/irccloud/irccloud-desktop/releases/tag/v0.4.0

**Comment by DavieDavieDave** [comment]
Can confirm this is no longer an issue.
