### ISSUE TITLE
Input lag

### ISSUE THREAD

**Issue by wirehack7** [irccloud/irccloud-desktop#92]
I'm using the client on Windows 10 Pro x64. Hardware specs:

- Intel i7-7700HQ
- 16GB Ram
- Intel HD Graphics 630

The input field is lagging when I type in. When I write in the field the letters are shown with a few ms lag. That's kinda annoying as it interrupts my typing behavior.
I hope there is a way to fix it.

**Comment by EvilTelephone** [comment]
I'm also having this issue. For me there's no lag when I first open the program, but after 5-10 minutes of having it running, the lag increases significantly. It gets so bad there's a 2-3 second delay between keypress and response.

Intel Core i7-8700k
16 GB RAM
Nvidia Geforce GTX 1080 Ti
Windows 10 Pro 1709
