### ISSUE TITLE
App is pixelated on high PPI screens

### ISSUE THREAD

**Issue by evanwalsh** [irccloud/irccloud-desktop#93]
The app does not look great on my MacBook Pro's high PPI screen. The latest version of Electron will handle this automatically, so an upgrade is all that's needed.

![](https://i.gyazo.com/63c75179b52f1f0f5701af7d42b1b1d6.png)

**Comment by jwheare** [comment]
This should be fixed in the next release.

**Comment by jwheare** [comment]
Latest release is now out: https://github.com/irccloud/irccloud-desktop/releases/tag/v0.4.0
