### ISSUE TITLE
TrayIcon

### ISSUE THREAD

**Issue by s0undt3ch** [irccloud/irccloud-desktop#94]
On KDE 5, the tray icon is not shown as being from irccloud and instead is shown as electron and no icon is seen.

![irccloud-tray](https://user-images.githubusercontent.com/300048/27331242-95d095b6-55b4-11e7-8492-c3cfdbaf45de.png)

When IRCCloud window is closed, there's no "show" on the tray icon to bring the window back, only quit.

**Comment by s0undt3ch** [comment]
I'm using plasma workspace 5

**Comment by MonJamp** [comment]
I'm also on KDE. It does say "IRCCloud" when hovering over however the other issues are still there.

**Comment by s0undt3ch** [comment]
Well, not even hovering for me as the screenshot shows...

**Comment by MonJamp** [comment]
The missing tray icon is a KDE bug, KDE doesn't resize icons for some reason. If you manually scale the icon to 24x24 the icon shows in the tray.

**Comment by jwheare** [comment]
The icon is fixed now (pending the next release). Electron doesn't support customising the tooltip for KDE, it just uses the package.json name: irccloud-desktop.

**Comment by jwheare** [comment]
Fixed in the latest release: https://github.com/irccloud/irccloud-desktop/releases/tag/v0.4.0
