### ISSUE TITLE
AppImage is using wrong icon.

### ISSUE THREAD

**Issue by AmandaCameron** [irccloud/irccloud-desktop#96]
Appolgies, hit enter by mistake.

Instead of using the image that's installed in ~/.local/share/icons/ the .desktop file being generated by the appimage is telling it to look for `appimagekit-irccloud-desktop` -- but the icons being installed are all called `appimagekit-irccloud` so they''re not found and thus no icon is shown.

**Comment by jwheare** [comment]
This should be fixed in the next release.

**Comment by jwheare** [comment]
Latest release is now out: https://github.com/irccloud/irccloud-desktop/releases/tag/v0.4.0
