### ISSUE TITLE
[Linux] desktop file is lacking a Categories= entry

### ISSUE THREAD

**Issue by probonopd** [irccloud/irccloud-desktop#98]
The desktop file is lacking a `Categories=` entry in the `*.desktop` file.

According to the [menu spec](https://standards.freedesktop.org/menu-spec/latest/apa.html),

> By including one of the Main Categories in an application's desktop entry file, the application will be ensured that it will show up in a section of the application menu dedicated to this category. If multiple Main Categories are included in a single desktop entry file, the entry may appear more than once in the menu. 

Hence, please add at least one of the following in the `Categories=` key.

Main Category | Description | Notes
-- | -- | --
AudioVideo | Application for presenting, creating, or processing multimedia (audio/video) |  
Audio | An audio application | Desktop entry must include AudioVideo as well
Video | A video application | Desktop entry must include AudioVideo as well
Development | An application for development |  
Education | Educational software |  
Game | A game |  
Graphics | Application for viewing, creating, or processing graphics |  
Network | Network application such as a web browser |  
Office | An office type application |  
Science | Scientific software |  
Settings | Settings applications | Entries may appear in a separate menu or as part of a 		"Control Center"
System | System application, "System Tools" such as say a log viewer or network monitor |  
Utility | Small utility application, "Accessories"

In addition, you could specify one or more from the longer list of [Additional Categories](https://standards.freedesktop.org/menu-spec/latest/apas02.html).

Please test the result with `desktop-file-validate` and make sure it passes.

electron-builder offers native support for this since [v19.22.1](https://github.com/electron-userland/electron-builder/releases/tag/v19.22.1).

Reference: https://github.com/AppImage/AppImageHub/issues/2

**Comment by jwheare** [comment]
This should be fixed in a2a70eb15af4d6cca1d4814077c450ab8e908b7f by adding `IRCClient` from Additional Categories. Is a main category still needed or is the `Network` type picked up? I couldn't see how to specify multiple categories.

**Comment by probonopd** [comment]
In XDG desktop files, like this: `Categories=Category1;Category2;` but I don't know how electron-builder handles this. In XDG desktop files, the first category should be one of the main categories. Please don't forget to run your desktop file through `desktop-file-validate` to see if it passes.

If someone could be so nice to let me know once a new version is available on GitHub Releases, I can run it through the test again.

**Comment by jwheare** [comment]
Alright, this seems to work: 7d13b7d

I downloaded the built appimage and manually tested it with `desktop-file-validate` on a mac (via homebrew). Any idea if there's a simple way to have this validation run automatically on travis ci electron-builder runs?

**Comment by probonopd** [comment]
Thank you very much.

Maybe it would be possible to do on Travis CI what you did on your local machine? But it may be overkill, since as long as the file is not changed  it should continue to work.

**Comment by jwheare** [comment]
Well, it was a bit annoying. I had to find the appimage ( which will change name on different release numbers), rename to .img, mount it, dig down into to find the file, then run it. So it’s possible, but as you say, probably overkill for me to setup in a manual Travis routing.

I’ll see if @develar would consider validating it automatically in the build process, maybe only if the validate-desktop-file program exists.

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/issues/2136

**Comment by jwheare** [comment]
Fixed in the latest release: https://github.com/irccloud/irccloud-desktop/releases/tag/v0.4.0

**Comment by probonopd** [comment]
Thank you, works for me.
