### ISSUE TITLE
Chat history is repeated

### ISSUE THREAD

**Issue by kedarX** [irccloud/irccloud-desktop#99]
**Issue**
History for last 10-15 chats on an irc channel is repeated twice. I believe those chats were after my mac was put to sleep last night and before I woke up today morning.

**Version**
0.3.0 (0.3.0.181) -- Using a an Active 1 year subscription.

**Comment by jwheare** [comment]
I believe this was resolved in the web app. Please reopen with screenshots if it's still happening.
